project:
  type: website
  output-dir: docs
#  resources:
#    - CNAME

website:
  title: "predme.com"
  google-analytics: "G-TMSZGFFJWF"
  navbar:
    logo: predme-logo.png
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



